services:
    rabbitmq:
        #image: rabbitmq:3.13-management-alpine
        image: hozanaci/rabbitmq:master
        container_name: rabbitmq
        volumes:
            - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            # Rename .env.dist to .env and set the values
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 127.0.0.1:5672:5672
            - 127.0.0.1:15672:15672