version: 2.1

jobs:
  build:
    resource_class: medium
    docker:
      - image: docker:25.0.2
        auth:
          username: hozanaci
          password: $DOCKERHUB_PASSWORD
    environment: 
      DOCKER_IMAGE: hozanaci/rabbitmq
      DOCKERHUB_USERNAME: hozanaci
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk --update add --no-cache docker docker-cli-compose git

      - run:
          name: Activate experimenta features
          command: |
            mkdir -p ~/.docker
            echo '{"experimental": true}' > ~/.docker/daemon.json

      - run:
          name: Create a new builder
          command: |
            docker buildx create --use --name hozana-builder
            docker buildx inspect --bootstrap

      - run:
          name: Build application Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            export DOCKER_BUILDKIT=1
            docker buildx build --provenance=true --no-cache -t $DOCKER_IMAGE:${CIRCLE_SHA1} --push .
            # DOCKER_BUILDKIT=1 docker build --provenance=true --no-cache -t $DOCKER_IMAGE:${CIRCLE_SHA1} .

      - run:
          name: Save image to dockerHub registry
          command: |
            docker push $DOCKER_IMAGE:${CIRCLE_SHA1}
  
  deploy:
    resource_class: medium
    docker:
      - image: docker:25.0.2
        auth:
          username: hozanaci
          password: $DOCKERHUB_PASSWORD
    environment: 
      DOCKER_IMAGE: hozanaci/rabbitmq
      DOCKERHUB_USERNAME: hozanaci
    
    steps:
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk --update add --no-cache docker docker-cli-compose git
      - run:
          name: Login into DockerHub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Recover release candidate
          command: |
            docker pull $DOCKER_IMAGE:${CIRCLE_SHA1}
      - run:
          name: Publish image to :branchname tag
          command: |
            docker tag $DOCKER_IMAGE:${CIRCLE_SHA1} $DOCKER_IMAGE:${CIRCLE_BRANCH}
            docker push $DOCKER_IMAGE:${CIRCLE_BRANCH}

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
